phrase:
  #access_token: my_phrase_access_token
  project_id: b95659c0e8e209dcd3471e54e8513ef2
  push:
    sources:
      - file: ./de_locale/locale_en.properties
        params:
          file_format: properties
          locale_id: eb6fa83febcad7125aec14c637275345
          update_translations: true
          tags: DE_Website , Bosch_Brand
      - file: ./uk_locale/locale_en.properties
        params:
          file_format: properties
          locale_id: eb6fa83febcad7125aec14c637275345
          update_translations: true
          tags: UK_Website , Siemens_Brand
 
  pull:
    targets:
      - file: ./all_translations/locale_de.properties
        params:
          file_format: properties
          locale_id: c28293e15bc19627dc6d920973df8c24
          
      - file: ./all_translations/locale_fr.properties
        params:
          file_format: properties
          locale_id: e8ebec66a2d836ca555f71b4e8663c84
   
      
          
          
